### ISSUE TITLE
There are sed command errors in build.sh

### ISSUE THREAD

**Issue by ChengWu-NJ** [zimbatm/ffmpeg-static#103]
modify bugs in build.sh

line276:
sed -i '' 's/-lgcc_s/-lgcc_eh/g' x265.pc
-->
sed -i 's/-lgcc_s/-lgcc_eh/g' x265.pc

line344:
sed -i "" "s/prefix=.*/prefix=${TARGET_DIR_SED}/" ./Makefile
-->
sed -i "s/prefix=.*/prefix=${TARGET_DIR_SED}/" ./Makefile

line361:
sed -i "" "s/vidstab SHARED/vidstab STATIC/" ./CMakeLists.txt
-->
sed -i "s/vidstab SHARED/vidstab STATIC/" ./CMakeLists.txt

**Comment by mmirold** [comment]
BSD sed (as used on MacOS X) needs those quotation marks after `-i`, i.e. the build fails on Mac after this change.
