### ISSUE TITLE
[Request to collaborate] I added SRT/RIST support and updated to FFmpeg 6

### ISSUE THREAD

**Issue by guilletrejo** [zimbatm/ffmpeg-static#108]
Hi! I've added those 2 protocols and updated the ffmpeg version. Can I please be added as a colaborator so I can create the PR?

Thanks!

**Comment by zimbatm** [comment]
Hi!

Sounds good, you don't need to request permission. Make a fork, and then send a PR:

https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by guilletrejo** [comment]
Thanks! I'll do that
