### ISSUE TITLE
Download errors

### ISSUE THREAD

**Issue by voltagex** [zimbatm/ffmpeg-static#39]
$ tar xzvf /media/sde1/home/voltagex/src/ffmpeg-static-master/dl/yasm-1.3.0.tar.gz
    --2015-10-15 08:36:30--  http://download.videolan.org/pub/x264/snapshots/last_x264.tar.bz2
    Resolving download.videolan.org (download.videolan.org)... 88.191.250.2
    Connecting to download.videolan.org (download.videolan.org)|88.191.250.2|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 726062 (709K) [application/octet-stream]
    Saving to: ‘STDOUT’
    
         0K .......... .......... .......... .......... ..........  7%  891K 1s
        50K .......... .......... .......... .......... .......... 14% 1.74M 1s
       100K .......... .......... .......... .......... .......... 21% 1.74M 0s
       150K .......... .......... .......... .......... .......... 28% 1.72M 0s
       200K .......... .......... .......... .......... .......... 35% 1.74M 0s
       250K .......... .......... .......... .......... .......... 42% 1.74M 0s
       300K .......... .......... .......... .......... .......... 49% 1.72M 0s
       350K .......... .......... .......... .......... .......... 56% 1.67M 0s
       400K .......... .......... .......... .......... .......... 63% 1.74M 0s
       450K .......... .......... .......... .......... .......... 70% 1.73M 0s
       500K .......... .......... .......... .......... .......... 77% 1.74M 0s
       550K .......... .......... .......... .......... .......... 84% 1.74M 0s
       600K .......... .......... .......... .......... .......... 91% 1.73M 0s
       650K .......... .......... .......... .......... .......... 98% 1.74M 0s
       700K .........                                             100%  109M=0.4s
    
    2015-10-15 08:36:31 (1.64 MB/s) - written to stdout [726062/726062]
    
    MD5 sum of the downloaded file does not match (file: f40642763bd979fea44c5c3fd73e00f0, requested: 2b712f196293bd04f4241e4f218e102d) - deleting download.
    --2015-10-15 08:36:31--  http://mirror2.openwrt.org/sources/last_x264.tar.bz2
    Resolving mirror2.openwrt.org (mirror2.openwrt.org)... 46.4.11.11
    Connecting to mirror2.openwrt.org (mirror2.openwrt.org)|46.4.11.11|:80... connected.
    HTTP request sent, awaiting response... 404 Not Found
    2015-10-15 08:36:31 ERROR 404: Not Found.
    
    Download failed.
    --2015-10-15 08:36:31--  http://downloads.openwrt.org/sources/last_x264.tar.bz2
    Resolving downloads.openwrt.org (downloads.openwrt.org)... 78.24.191.177
    Connecting to downloads.openwrt.org (downloads.openwrt.org)|78.24.191.177|:80... connected.
    HTTP request sent, awaiting response... 404 Not Found
    2015-10-15 08:36:31 ERROR 404: Not Found.
    
    Download failed.
    No more mirrors to try - giving up.

**Comment by dingyaguang117** [comment]
the same
