### ISSUE TITLE
libvpx updated

### ISSUE THREAD

**Issue by crayxt** [zimbatm/ffmpeg-static#40]
Latest version is libvpx-1.5.0.tar.bz2

**Comment by zimbatm** [comment]
This project is powered by contributors, if you send a PR I will gladly merge

**Comment by crayxt** [comment]
I am still not done building ;)

**Comment by crayxt** [comment]
Tried ffmpeg 2.8.2 together with libvpx-1.5.0, so FFmpeg needs this patch integrated due to libvpx changes
http://git.videolan.org/?p=ffmpeg.git;a=blobdiff;f=libavcodec/libvpxenc.c;h=992122c98276d0fda12f0a6117bc884ec63c9d41;hp=5f397830871b35e9e977c58b1b2abb57aef6f69c;hb=6540fe04a3f9a11ba7084a49b3ee5fa2fc5b32ab;hpb=6b41b4414934cc930468ccd5db598dd6ef643987

Better use older libvpx for now, which can be found at http://storage.googleapis.com/downloads.webmproject.org/releases/webm/libvpx-1.5.0.tar.bz2

**Comment by zimbatm** [comment]
Thanks for the report ! I guess this needs a newer ffmpeg version

**Comment by Silex** [comment]
@zimbatm:  ffmpeg-static is slowly but surely becoming out of date, and STVS has no time to maintain it... would you like to become the maintainer at the zimbatm/ffmepg-static url?

**Comment by zimbatm** [comment]
sure, feel free to transfer the repo

**Comment by Silex** [comment]
@zimbatm: alright, you just need to accept it in github's interface now :)

**Comment by Silex** [comment]
@zimbatm?

**Comment by crayxt** [comment]
Closed due to being old now
