### ISSUE TITLE
Ownership transfer

### ISSUE THREAD

**Issue by zimbatm** [zimbatm/ffmpeg-static#41]
@Silex let's not pollute the other isssue.

I didn't see any ownership transfer request yet

**Comment by Silex** [comment]
"This repository is being transferred to @zimbatm."

**Comment by Silex** [comment]
Check at different places? If you really don't find it, I'll abort the transfer & start over.

**Comment by zimbatm** [comment]
Found :)

**Comment by Silex** [comment]
:+1: 

I deleted the comments on the other issue.
