### ISSUE TITLE
Option to not rebuid existing binaries

### ISSUE THREAD

**Issue by andreipoe** [zimbatm/ffmpeg-static#50]
Hi @zimbatm.

I think it would be a welcome addition to have an option to avoid rebuilding existing files. For example, if a build stops before it was partially done, we could avoid recompiling everything by having `tar` not replace existing files and only run `./configure` again if it didn't complete successfully. I've been experimenting with this and it seems to work fine.

The way I see it, there are two ways to implement this: we could make what I described above the default behaviour and provide a full rebuild option (similar to `make -B`), or the other way around, where the user could request to not rebuild existing binaries. Personally, I would go for the first option because it seems to waste less time, but I was wondering if you have any preference with that.

Thanks,

Andrei

**Comment by zimbatm** [comment]
Hey @andreipoe,

the first option sounds good to me :)

**Comment by andreipoe** [comment]
I think this is good enough. It avoids re-configuring, and since the file timestamps aren't changed, then `make` will not rebuild unless specifically required as part of the script. I wanted to pass on `-B` to `make` when the user runs `./build.sh -B`, but that seems to be very hit-or-miss with autotools, to let's just leave it as it is now. Users can always delete `bin`, `build` and `target` manually to force a clean build.
