### ISSUE TITLE
ERROR: x265 not found using pkg-config

### ISSUE THREAD

**Issue by Vuzrak** [zimbatm/ffmpeg-static#67]
Getting the error "ERROR: x265 not found using pkg-config" when it trys to build ffmpeg.

This is on Ubuntu 17.10, I'm able to build it fine with x265 if I do it manually from the instructions from "https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu".

**Comment by r4dius** [comment]
Same issue on ubuntu 18.04 when building static version with --extra-ldexeflags="-static" in the config.log we get : 
/usr/bin/x86_64-linux-gnu-ld: cannot find -lgcc_s
/usr/bin/x86_64-linux-gnu-ld: cannot find -lgcc_s
not sure why yet

**Comment by Zalewa** [comment]
PR #79 fixes this.

**Comment by zimbatm** [comment]
thanks @Zalewa !
